name: 'dbt_newday_coding_assignment'
version: '1.0'
config-version: 2

profile: 'profile_dbt_newday_coding_assignment'

model-paths: ["models"]
macro-paths: ["macro"]     # your folder is singular: macro
seed-paths: ["seeds"]      # put CSVs under ./seeds/...

models:
  dbt_newday_coding_assignment:
    
    staging:
      +materialized: table
      +enabled: true
      +schema: staging
    
    intermediate:
      +materialized: table
      +enabled: true
      +schema: staging

seeds:
  dbt_newday_coding_assignment:
    +schema: raw
    +quote_columns: false


vars:
  start_date: 2028-01-16
  end_date: 2028-01-17


#sqlfluff fix --templater dbt /Users/rahulrajasekharan/vscode_proj/newday-dbt/newday-coding-task/dbt/dbt_newday_coding_assignment/.sqlfluff models/intermediate/