name: 'dbt_newday_coding_assignment'
version: '1.0'
config-version: 2

profile: 'profile_dbt_newday_coding_assignment'

model-paths: ["models"]
macro-paths: ["macro"]     # your folder is singular: macro
seed-paths: ["seeds"]      # put CSVs under ./seeds/...

models:
  dbt_newday_coding_assignment:
    raw:
      +materialized: table
      +enabled: true
      +schema: raw
    
    staging:
      +materialized: table
      +enabled: true
      +schema: staging

seeds:
  dbt_newday_coding_assignment:
    +schema: raw
    +quote_columns: false