profile_dbt_newday_coding_assignment:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 192.168.0.208
      user: admin
      password: admin
      port: 5432
      dbname: dbt_db
      schema: public
      threads: 1
