version: 2

sources:
  - name: raw
    database: mydb
    schema: raw_layer
    tables:
      - name: customers
      - name: products
      - name: orders
      - name: order_items
      - name: payments