version: 2

models:
  - name: my_first_model
    description: "A basic model that says hello"
    columns:
      - name: greeting
        description: "A simple greeting"
      - name: today
        description: "The current date"
