version: "3.9"

services:
  postgres:
    build: .
    image: custom-postgres:1.0
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dbt_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: